# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(max_length=200)),
                ('actor_surname', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_num', models.PositiveIntegerField()),
                ('rec_date', models.DateField(auto_now_add=True)),
                ('out_num', models.CharField(max_length=50)),
                ('out_date', models.DateField()),
                ('rec_desc', models.CharField(max_length=200)),
                ('control_date', models.DateField()),
                ('rec_deal', models.PositiveIntegerField()),
                ('action_date', models.DateField()),
                ('rec_actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Actor')),
                ('rec_org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Org')),
            ],
        ),
    ]
