# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_num', models.PositiveIntegerField()),
                ('rec_date', models.DateField(auto_now_add=True)),
                ('out_num', models.CharField(max_length=50)),
                ('out_date', models.DateField()),
                ('rec_desc', models.CharField(max_length=200)),
                ('control_date', models.DateField()),
                ('inrec_deal', models.PositiveIntegerField()),
                ('action_date', models.DateField()),
                ('rec_actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Actor')),
                ('rec_org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Org')),
            ],
        ),
        migrations.CreateModel(
            name='OutRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_num', models.PositiveIntegerField()),
                ('rec_date', models.DateField(auto_now_add=True)),
                ('rec_desc', models.CharField(max_length=200)),
                ('num_serv', models.PositiveIntegerField()),
                ('num_mainpages', models.PositiveIntegerField()),
                ('num_optpages', models.PositiveIntegerField()),
                ('in_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.InRecord')),
                ('rec_actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Actor')),
                ('rec_org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Org')),
            ],
        ),
        migrations.RemoveField(
            model_name='record',
            name='rec_actor',
        ),
        migrations.RemoveField(
            model_name='record',
            name='rec_org',
        ),
        migrations.DeleteModel(
            name='Record',
        ),
    ]
