# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 06:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_auto_20160915_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inrecord',
            name='inrec_deal',
        ),
        migrations.AddField(
            model_name='inrecord',
            name='rec_deal',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='inrecord',
            name='action_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='inrecord',
            name='control_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='inrecord',
            name='rec_actor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='journal.Actor'),
        ),
        migrations.AlterField(
            model_name='outrecord',
            name='in_ref',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='journal.InRecord'),
        ),
        migrations.AlterField(
            model_name='outrecord',
            name='num_serv',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
