# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_null_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inrecord',
            name='rec_num',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='outrecord',
            name='rec_num',
            field=models.CharField(max_length=50),
        ),
    ]
